services:
  mental-health-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    container_name: mental-health-app
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mentaldb
  mongo:
    image: mongo:latest
    container_name: mental-health-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
